# Generated by Django 5.0.4 on 2024-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='rank',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
