# Generated by Django 5.0.4 on 2024-04-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0002_searchdata_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchData',
        ),
    ]
